services:

  grafana:
    image: grafana/grafana
    container_name: lab_grafana
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - lab240-monitoring
    environment:
      # - GF_LOG_LEVEL=debug 
      # - GF_LOG.CONSOLE_LEVEL=debug
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=${ALLOW_SIGN_UP:-false}
      - GF_AUTH_ANONYMOUS_ENABLED=${ANONYMOUS_ENABLED:-true}

networks:
  lab240-monitoring:

volumes:
  grafana-data:
