services:

  grafana:
    image: grafana/grafana
    container_name: lab_grafana
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - lab240-monitoring
    environment:
      # - GF_LOG_LEVEL=debug 
      # - GF_LOG.CONSOLE_LEVEL=debug
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admingrafana}
      - GF_USERS_ALLOW_SIGN_UP=${ALLOW_SIGN_UP:-false}
      - GF_AUTH_ANONYMOUS_ENABLED=${ANONYMOUS_ENABLED:-true}

  influxdb:
    image: influxdb:latest
    container_name: lab_influxdb2
    restart: always
    volumes:
      - ./influxdb2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    networks:
      - lab240-monitoring

  influxdb_cli:
    image: influxdb:latest
    profiles:
      - donotstart
    volumes:
      - ./influxdb2:/var/lib/influxdb2:rw
      # - ./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:rw
      # - ./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:rw
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${ADMIN_USER:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${ADMIN_PASSWORD:-admininflux}
      - DOCKER_INFLUXDB_INIT_ORG=${ORG:-lab240}
      - DOCKER_INFLUXDB_INIT_BUCKET=${BUCKET:-bucket}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${ADMIN_TOKEN:-IvuRlZ6ZJR8f6vzzK54ywtEB_xvFuXS6DrGql4bTABEkgum8BhHBZ4T10XNEdhB5PeoB5WZpXglQWv9LaEisvQ==}
      # - INFLUXD_TLS_CERT=/etc/ssl/influxdb-selfsigned.crt
      # - INFLUXD_TLS_KEY=/etc/ssl/influxdb-selfsigned.key
    entrypoint: ["./entrypoint.sh"]
    networks:
      - lab240-monitoring
    restart: on-failure:10

  telegraf:
    image: telegraf
    container_name: lab_telegraf
    restart: always
    hostname: host1
    links:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - lab240-monitoring
    environment: 
      - DOCKER_INFLUXDB_INIT_ORG=${ORG:-lab240}
      - DOCKER_INFLUXDB_INIT_BUCKET=${BUCKET:-bucket}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${ADMIN_TOKEN:-IvuRlZ6ZJR8f6vzzK54ywtEB_xvFuXS6DrGql4bTABEkgum8BhHBZ4T10XNEdhB5PeoB5WZpXglQWv9LaEisvQ==}

networks:
  lab240-monitoring:

volumes:
  grafana-data:
